language: node_js

node_js: node

cache: yarn

script: yarn tsc --noEmit && yarn dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
